import fs from 'node:fs';

const template = name => fs.readFileSync(new URL('../templates/' + name + '.md', import.meta.url), 'utf8');
const address = 'Один checkout/worktree имеет один current plan в .harness/plans/todo-plan.md. Команды не требуют session selector; N — текущая plan_revision из recovery/status. Для независимой параллельной работы используй отдельный Git worktree.';
const topics = {
  'review:acknowledge': () => './scripts/workflow review:acknowledge\nПеред финальным вопросом при NEEDS_USER отметьте, что сообщаете проблему пользователю. После этого ждите его ответа. Не разрешает retry или публикацию.',
  'review:run': () => './scripts/workflow review:run [--max-turns 30] [--timeout-ms 900000]\nДолгая команда: exec_command и ожидание session ID через write_stdin, без nohup или повторного запуска. Opus 5.5 / high, одна сессия, resume; до четырёх раундов. Прочитайте review_file из результата. NEEDS_USER означает: сообщить причину и спросить пользователя. На успешное согласие также дайте свою позицию; затем review:publish. Для исправлений — review:prepare с той же scope_id и response. Память разрешена. При прерывании сначала review:status.',
  'review:prepare': () => `./scripts/workflow review:prepare --input .harness/runtime/review-input.json
Сначала запишите спецификацию в docs/planning. Полная минимальная форма входа (замените предметные поля, проверки и пути своей задачей):
${JSON.stringify({recipient_session_id:'<Session ID из стартового сообщения>',scope:{scope_id:'new-feature',objective:'Реализовать согласованную задачу',approval_note:'Пользователь поручил подготовить и выполнить этот план.',acceptance_criteria:['Проверяемый результат'],approved_scope:{functional_paths:['src/feature.mjs'],documentation_paths:['docs/planning/feature.md','README.md']},context_pack:{documents:[{path:'docs/planning/feature.md',required:true}],include_last_completed_task:false,dependency_task_ids:[]},tasks:[{id:'T001',title:'Реализовать функцию',why:'Получить согласованный результат',dependencies:[],functional_paths:['src/feature.mjs'],documentation_paths:['README.md'],verification_ids:[],acceptance_criteria:['Функция работает'],expected_commit_message:'feat: реализовать функцию'}]},documents:['docs/planning/feature.md']},null,2)}
verification_ids берите из действующей .harness/workflow.json; пустой список допустим только там, где проверки действительно не нужны. Для нового проекта сначала настройте проверки через config:apply, сохранив остальные поля. DOCS и delivery задавайте по правилам Kit.
В Web Pilot замените recipient_session_id точным Session ID из стартового сообщения. Явный scope.session_id также принимается как метаданные доставки; если указаны оба поля, они обязаны совпадать. Это получатель продолжения, не владелец плана. Пропуск ID при новом цикле — REVIEW_RECIPIENT. Вне Web Pilot явно укажите recipient_mode: manual и не задавайте ID: агент сам ожидает CLI и ведёт цикл.
Следующий prepare того же run сохраняет получателя. Для другого ID нужен recipient_change_note с прямым поручением пользователя о подхвате; замечание не придумывайте. Старый цикл без ID нельзя автоматически привязать к выбранному чату. Не редактируйте state.json вручную.
Каждая часть spec нужна в documentation_paths и required context_pack. Снимки остаются вне Git. Требуется Review ON и NONE. После исправлений повторите prepare с той же scope_id и полем response (позиция автора). Затем review:run; при согласии review:publish. При NEEDS_USER выполните review:acknowledge перед вопросом пользователю и ждите решения.`,
  'review:status': () => './scripts/workflow review:status\nПолитика и состояние checkout, файлы результата и ошибка. Политикой управляет кнопка Web Pilot; отсутствие state.json означает OFF. При OFF план публикуется обычным путём, включая прежний спор.',
  'review:cancel': () => './scripts/workflow review:cancel --note "Решение пользователя"\nОтменить незапущенный цикл и освободить checkout. Не отменяет неизвестный работающий процесс и не удаляет опубликованный план.',
  'review:resolve': () => './scripts/workflow review:resolve --action retry|publish|cancel --note "Решение пользователя"\nТолько после ответа пользователя при NEEDS_USER: повторить, опубликовать или отменить. При неизвестном исходе запуска сначала установите его завершение. Не выдавайте собственное решение за пользовательское.',
  'review:publish': () => './scripts/workflow review:publish\nПубликация согласованной пары через createScope. Проверяет SHA, HEAD/revision под блокировкой, коммитит только одобренные документы. После прерывания status/repair перед повтором. При OFF согласия Claude не требуется.',
  'plan:create': () => template('PLAN') + '\n\n' + template('SPEC'),
  'plan:carryover': () => './scripts/workflow plan:carryover --input carryover.json --expected-revision N\nВход: {"scope":"old-scope","id":"new-scope","approval_note":"Прямое поручение пользователя"}; objective необязателен. Чистый checkout, без активной микрозадачи. Новый план из незавершённых задач фиксируется одним коммитом; source_commit указывает на прежний план в Git, архивные копии не создаются. После прерывания используйте status/repair, повтор после успеха безопасен. Это отдельное закрытие с переносом, обычный archive по-прежнему требует завершения задач.',
  'plan:extend': () => template('CONTINUE'),
  'task:start': () => template('STAGES') + '\n\n' + './scripts/workflow task:start T001\nНачни существующую микрозадачу перед изменением исходников. После успешного старта выполняй работу без дополнительного status. Затем commit --task T001.',
  commit: () => './scripts/workflow commit --task T001\nЗапускает проверки задачи и сохраняет фактические изменения одним коммитом. Если проверка уже входит в commit, не запускай её отдельно на том же состоянии.\nПри неоднозначном составе: --input files.json, где {"files":["src/main.mjs","package.json"]}.\nПосле ошибки исправь указанную причину; после прерывания проверь status перед повтором.',
  'docs:commit': () => './scripts/workflow docs:commit --input files.json --message "docs: уточнить документы"\nfiles.json: {"files":["README.md","packages/example/README.md"]}. Только .md вне .harness/, без активной задачи, NONE или ACTIVE. Управляемая секция AGENTS.md сохраняется побайтно. Проверяются схема, состав и размер; suite приложения не запускается. Правки сохраняются при ошибке.',
  'task:update': () => './scripts/workflow task:update --task T001 --input update.json --expected-revision N\nПример update.json: {"files":["src/main.mjs","src/helper.mjs"],"acceptance":["Основной сценарий работает"]}.\nИзменяет контракт незавершённой задачи. Одно добавление исходника не требует task:update: commit сохраняет фактический состав.',
  status: () => './scripts/workflow status\nСвежие состояние плана, задачи, Git, revision и незавершённая транзакция. Не заменяет проверку файлов перед записью.',
  recover: () => './scripts/workflow recover --format text\nПолный стартовый контекст; --format json и --format packet возвращают также parts с байтами, символами и SHA-256. Части вместе с заголовками ограничены budget.document_bytes. context_pack.documents: path, required, revision (WORKTREE либо точный SHA); heading_path принят для совместимости, документ включается целиком. Дедупликация по path/revision, required побеждает. Коммиты и диффы читаются агентом по ссылкам перед зависимой реализацией. Не перечитывай уже доставленный неизменившийся пакет.',
  validate: () => './scripts/workflow validate\nПроверяет согласованность плана и Git, не выполняет продуктовые тесты.',
  'plan:view': () => './scripts/workflow plan:view\nПоказывает единственный current plan этого checkout. --session временно принимается только как compatibility metadata.',
  'plan:apply': () => './scripts/workflow plan:apply --input changes.json --expected-revision N\nУточняет текущий план. Для добавления задач проще plan:extend. Сохраняй DONE-задачи и машинные статусы; пример разрешённого изменения: {"acceptance_criteria":["Проверяемый результат"]}.',
  'project:rename': () => './scripts/workflow project:rename --name <имя> --expected-revision N\nМеняет имя проекта в current plan (заголовок плана и recovery), например после переименования папки, и обновляет пути git-hooks в kit-manifest. Только без активной микрозадачи; один служебный коммит. Папку команда не переименовывает.',
  'config:apply': () => './scripts/workflow config:apply --input config.json\nПолная конфигурация проверок, не частичный patch. Прочитай .harness/workflow.json и сохрани остальные поля. Для нового прототипа plan:create настраивает проверки из checks.',
  repair: () => './scripts/workflow repair --dry-run\nПолучить конкретный repair_id, затем --apply <repair_id>. --cancel <repair_id> отменяет неподтверждённую подготовку commit, сохраняя рабочие файлы. Не удаляй журнал вручную.',
  archive: () => './scripts/workflow archive --scope <scopeId> --approval-note "Прямое поручение пользователя"\nТолько по отдельному поручению, после завершения всех задач. Завершённый план не требует архивирования.',
  'plan:prepare': () => 'Команда удалена. Новый chat продолжает текущий plan этого checkout; независимая работа ведётся в отдельном Git worktree.',
  'plan:bind': () => 'Команда удалена. Chat session больше не является владельцем Workflow Kit plan.',
  'plan:adopt': () => 'Команда удалена. Legacy plans остаются read-only history и не выбирают runtime state.',
  'scope:create': () => './scripts/workflow scope:create --input scope.json\nНизкоуровневый полный контракт scope. Для нового прототипа используй plan:create --help: Kit сам сформирует служебные поля.',
  install: () => './scripts/workflow install --project <absolute-path> --mode new\nУстановка Kit в новый проект; mode connect — существующий проект. --update обновляет принадлежащие Kit файлы с проверкой конфликтов.',
  'install:commit': () => './scripts/workflow install:commit --project <absolute-path>\nЗавершение bootstrap после настройки Git identity.',
  inspect: () => './scripts/workflow inspect --project <absolute-path>\nПроверка состояния установки без изменений.',
  doctor: () => './scripts/workflow doctor --project <absolute-path>\nДиагностика установки, ссылок и hooks.',
  remove: () => './scripts/workflow remove --project <absolute-path> --dry-run\nПоказывает удаление принадлежащих Kit неизменённых файлов; применение только по явному поручению.',
  'hook:ack': () => './scripts/workflow hook:ack --marker <DELIVERY-MARKER> --client codex\nПодтверждает только реально доставленный lifecycle marker.',
  hook: () => './scripts/workflow hook session-start\nСлужебный lifecycle endpoint; JSON события поступает в stdin.',
  'git-hook': () => './scripts/workflow git-hook <pre-commit|commit-msg|post-commit|pre-push>\nСлужебная проверка управляемого Git commit; обычно вызывается Git автоматически.'
};
export function commandHelp(command = 'help') {
  if (command === 'help') return 'Project Workflow Kit\n\n' + address + '\n\n' + Object.keys(topics).map(name => './scripts/workflow ' + name + ' --help').join('\n');
  if (!topics[command]) throw Object.assign(new Error('Неизвестная команда справки: ' + command), {code: 'UNKNOWN_COMMAND'});
  return 'Project Workflow Kit — ' + command + '\n\n' + address + '\n\n' + topics[command]();
}
